paths:
  .github/workflows/yaml-anchor-basic.yaml:
    ignore:
      - '"paths" section must be sequence node but got alias node with "" tag'

  .github/workflows/job-needs-skip-handling-bad.yaml:
    ignore:
      - 'constant expression "false" in condition. remove the if: section'

  # cannot control Copilot Agentic workflow compiled yamnl
  .github/workflows/agentics-maintenance.yml:
    ignore:
      - "string should not be empty"

  # cannot control Copilot Agentic workflow compiled yamnl
  .github/workflows/monthly-oss-repo-status.lock.yml:
    ignore:
      - 'element of "schedule" section must be mapping and must contain one key "cron"'
      - "shellcheck reported issue in this script: SC2086:info:1:1: Double quote to prevent globbing and word splitting"
      - "shellcheck reported issue in this script: SC2129:style:1:1: Consider using { cmd1; cmd2; } >> file instead of individual redirects"
      - "shellcheck reported issue in this script: SC2015:info:5:15: Note that A && B || C is not if-then-else. C may run when A is true"
