ACCEPT_EULA="Y"
ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE="/opt/actionarchivecache"
AGENT_TOOLSDIRECTORY="/opt/hostedtoolcache"
ANDROID_HOME="/usr/local/lib/android/sdk"
ANDROID_NDK="/usr/local/lib/android/sdk/ndk/25.2.9519653"
ANDROID_NDK_HOME="/usr/local/lib/android/sdk/ndk/25.2.9519653"
ANDROID_NDK_LATEST_HOME="/usr/local/lib/android/sdk/ndk/26.1.10909125"
ANDROID_NDK_ROOT="/usr/local/lib/android/sdk/ndk/25.2.9519653"
ANDROID_SDK_ROOT="/usr/local/lib/android/sdk"
ANT_HOME="/usr/share/ant"
AZURE_EXTENSION_DIR="/opt/az/azcliextensions"
BOOTSTRAP_HASKELL_NONINTERACTIVE="1"
CHROMEWEBDRIVER="/usr/local/share/chromedriver-linux64"
CHROME_BIN="/usr/bin/google-chrome"
CI="true"
CONDA="/usr/share/miniconda"
CONTEXT="{}"
DEBIAN_FRONTEND="noninteractive"
DEPLOYMENT_BASEPATH="/opt/runner"
DOTNET_MULTILEVEL_LOOKUP="0"
DOTNET_NOLOGO="1"
DOTNET_SKIP_FIRST_TIME_EXPERIENCE="1"
EDGEWEBDRIVER="/usr/local/share/edge_driver"
GECKOWEBDRIVER="/usr/local/share/gecko_driver"
GHCUP_INSTALL_BASE_PREFIX="/usr/local"
GITHUB_ACTION="__run"
GITHUB_ACTIONS="true"
GITHUB_ACTION_REF=""
GITHUB_ACTION_REPOSITORY=""
GITHUB_ACTOR="guitarrapc"
GITHUB_ACTOR_ID="3856350"
GITHUB_API_URL="https://api.github.com"
GITHUB_BASE_REF="main"
<<<<<<< HEAD
GITHUB_ENV="/home/runner/work/_temp/_runner_file_commands/set_env_075a9312-16d2-4d6f-a6b6-fcebf76d347b"
GITHUB_EVENT_NAME="pull_request_target"
GITHUB_EVENT_PATH="/home/runner/work/_temp/_github_workflow/event.json"
GITHUB_GRAPHQL_URL="https://api.github.com/graphql"
GITHUB_HEAD_REF="feature/env"
GITHUB_JOB="dump-context"
GITHUB_OUTPUT="/home/runner/work/_temp/_runner_file_commands/set_output_075a9312-16d2-4d6f-a6b6-fcebf76d347b"
GITHUB_PATH="/home/runner/work/_temp/_runner_file_commands/add_path_075a9312-16d2-4d6f-a6b6-fcebf76d347b"
=======
GITHUB_ENV="/home/runner/work/_temp/_runner_file_commands/set_env_40aeed9e-be8d-40f4-9a38-cdb9e5a46d83"
GITHUB_EVENT_NAME="pull_request_target"
GITHUB_EVENT_PATH="/home/runner/work/_temp/_github_workflow/event.json"
GITHUB_GRAPHQL_URL="https://api.github.com/graphql"
GITHUB_HEAD_REF="feature/tag"
GITHUB_JOB="dump-context"
GITHUB_OUTPUT="/home/runner/work/_temp/_runner_file_commands/set_output_40aeed9e-be8d-40f4-9a38-cdb9e5a46d83"
GITHUB_PATH="/home/runner/work/_temp/_runner_file_commands/add_path_40aeed9e-be8d-40f4-9a38-cdb9e5a46d83"
>>>>>>> main
GITHUB_REF="refs/heads/main"
GITHUB_REF_NAME="main"
GITHUB_REF_PROTECTED="false"
GITHUB_REF_TYPE="branch"
GITHUB_REPOSITORY="guitarrapc/githubactions-lab"
GITHUB_REPOSITORY_ID="257465468"
GITHUB_REPOSITORY_OWNER="guitarrapc"
GITHUB_REPOSITORY_OWNER_ID="3856350"
GITHUB_RETENTION_DAYS="90"
GITHUB_RUN_ATTEMPT="1"
<<<<<<< HEAD
GITHUB_RUN_ID="6793559825"
GITHUB_RUN_NUMBER="389"
GITHUB_SERVER_URL="https://github.com"
GITHUB_SHA="3c83bfce67ceb372aced2afa7014f29ff9802be3"
GITHUB_STATE="/home/runner/work/_temp/_runner_file_commands/save_state_075a9312-16d2-4d6f-a6b6-fcebf76d347b"
GITHUB_STEP_SUMMARY="/home/runner/work/_temp/_runner_file_commands/step_summary_075a9312-16d2-4d6f-a6b6-fcebf76d347b"
GITHUB_TRIGGERING_ACTOR="guitarrapc"
GITHUB_WORKFLOW="auto dump context"
GITHUB_WORKFLOW_REF="guitarrapc/githubactions-lab/.github/workflows/auto_dump_context.yaml@refs/heads/main"
GITHUB_WORKFLOW_SHA="3c83bfce67ceb372aced2afa7014f29ff9802be3"
=======
GITHUB_RUN_ID="6794643068"
GITHUB_RUN_NUMBER="408"
GITHUB_SERVER_URL="https://github.com"
GITHUB_SHA="82efa4b040ffc6da15574cd852c43e6f05e41c34"
GITHUB_STATE="/home/runner/work/_temp/_runner_file_commands/save_state_40aeed9e-be8d-40f4-9a38-cdb9e5a46d83"
GITHUB_STEP_SUMMARY="/home/runner/work/_temp/_runner_file_commands/step_summary_40aeed9e-be8d-40f4-9a38-cdb9e5a46d83"
GITHUB_TRIGGERING_ACTOR="guitarrapc"
GITHUB_WORKFLOW="auto dump context"
GITHUB_WORKFLOW_REF="guitarrapc/githubactions-lab/.github/workflows/auto_dump_context.yaml@refs/heads/main"
GITHUB_WORKFLOW_SHA="82efa4b040ffc6da15574cd852c43e6f05e41c34"
>>>>>>> main
GITHUB_WORKSPACE="/home/runner/work/githubactions-lab/githubactions-lab"
GOROOT_1_19_X64="/opt/hostedtoolcache/go/1.19.13/x64"
GOROOT_1_20_X64="/opt/hostedtoolcache/go/1.20.10/x64"
GOROOT_1_21_X64="/opt/hostedtoolcache/go/1.21.3/x64"
GRADLE_HOME="/usr/share/gradle-8.4"
HOME="/home/runner"
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS="3650"
HOMEBREW_NO_AUTO_UPDATE="1"
<<<<<<< HEAD
INVOCATION_ID="4d65d85eab424519989926e367eeea86"
=======
INVOCATION_ID="9db3931acce145d7b154950c9f06d406"
>>>>>>> main
ImageOS="ubuntu22"
ImageVersion="20231030.2.0"
JAVA_HOME="/usr/lib/jvm/temurin-11-jdk-amd64"
JAVA_HOME_11_X64="/usr/lib/jvm/temurin-11-jdk-amd64"
JAVA_HOME_17_X64="/usr/lib/jvm/temurin-17-jdk-amd64"
JAVA_HOME_21_X64="/usr/lib/jvm/temurin-21-jdk-amd64"
JAVA_HOME_8_X64="/usr/lib/jvm/temurin-8-jdk-amd64"
<<<<<<< HEAD
JOURNAL_STREAM="8:17401"
=======
JOURNAL_STREAM="8:17644"
>>>>>>> main
LANG="C.UTF-8"
LEIN_HOME="/usr/local/lib/lein"
LEIN_JAR="/usr/local/lib/lein/self-installs/leiningen-2.10.0-standalone.jar"
NVM_DIR="/home/runner/.nvm"
OLDPWD
OUTPUT_PATH="contexts/export"
PATH="/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
PERFLOG_LOCATION_SETTING="RUNNER_PERFLOG"
PIPX_BIN_DIR="/opt/pipx_bin"
PIPX_HOME="/opt/pipx"
POWERSHELL_DISTRIBUTION_CHANNEL="GitHub-Actions-ubuntu22"
PWD="/home/runner/work/githubactions-lab/githubactions-lab"
RUNNER_ARCH="X64"
RUNNER_ENVIRONMENT="github-hosted"
<<<<<<< HEAD
RUNNER_NAME="GitHub Actions 24"
=======
RUNNER_NAME="GitHub Actions 15"
>>>>>>> main
RUNNER_OS="Linux"
RUNNER_PERFLOG="/home/runner/perflog"
RUNNER_TEMP="/home/runner/work/_temp"
RUNNER_TOOL_CACHE="/opt/hostedtoolcache"
<<<<<<< HEAD
RUNNER_TRACKING_ID="github_e9568c9d-1b5f-44d2-865e-b1ed347dcf85"
=======
RUNNER_TRACKING_ID="github_9deca2c7-b78f-4105-8939-0a22b8deff2c"
>>>>>>> main
RUNNER_USER="runner"
RUNNER_WORKSPACE="/home/runner/work/githubactions-lab"
SELENIUM_JAR_PATH="/usr/share/java/selenium-server.jar"
SGX_AESM_ADDR="1"
SHLVL="1"
STATS_BLT="true"
STATS_EXT="true"
STATS_EXTP="https://provjobdsettingscdn.blob.core.windows.net/settings/provjobdsettings-0.5.154/provjobd.data"
STATS_NM="true"
STATS_RDCL="true"
STATS_TIS="mining"
STATS_TRP="true"
STATS_UE="true"
STATS_V3PS="true"
STATS_VMD="true"
SWIFT_PATH="/usr/share/swift/usr/bin"
<<<<<<< HEAD
SYSTEMD_EXEC_PID="581"
=======
SYSTEMD_EXEC_PID="576"
>>>>>>> main
USER="runner"
VCPKG_INSTALLATION_ROOT="/usr/local/share/vcpkg"
XDG_CONFIG_HOME="/home/runner/.config"
XDG_RUNTIME_DIR="/run/user/1001"
