name: container job
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  container:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    container:
      image: golang:1.25@sha256:dd7d32e19b28621cd982082397fc0510d396805b717d5e77466aa2dd692340de
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Show Go version
        run: go version
      - name: Run Go program
        run: go run main.go
        working-directory: ./src/go
