name: dotnet lint
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1 # At AM10:00 JST on Monday

jobs:
  lint_csharp:
    permissions:
      contents: write
      pull-requests: write
    uses: guitarrapc/actions/.github/workflows/reusable-dotnet-lint.yaml@main
    with:
      sln-root: "src/dotnet/"
