name: parallel (background)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  uses-background:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
        background: true
      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 10.0.x
        background: true
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.25"
        background: true

      - name: Wait background job
        wait-all:

      - name: Build dotnet
        id: build-dotnet # case insensitive
        run: dotnet build ./src/dotnet -o publish/dotnet
        background: true

      - name: Build go
        id: build-go
        run: go build -o ../../publish/go/
        working-directory: ./src/go/
        background: true

      - name: Build go-db
        id: build-go-db
        run: go build -o ../../publish/go-db/
        working-directory: ./src/go-db/
        background: true

      - name: Check build results
        run: ls -l ./publish/
        continue-on-error: true

  cancel:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build dotnet
        id: build-dotnet # case insensitive
        run: dotnet build ./src/dotnet -o publish/dotnet
        background: true

      - name: Build go
        id: build-go
        run: go build -o ../../publish/go/
        working-directory: ./src/go/
        background: true

      - name: Build go-db
        id: build-go-db
        run: go build -o ../../publish/go-db/
        working-directory: ./src/go-db/
        background: true

      - name: Check build results
        run: ls -l ./publish/
        continue-on-error: true

      # if not allowed
      - name: Cancel background job
        cancel: build-dotnet

      - name: Cancel background job
        cancel: build-go

      - name: Cancel background job
        cancel: build-go-db

      - name: Check build results after wait
        run: ls -lR ./publish/

  wait:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build dotnet
        id: build-dotnet
        run: dotnet build ./src/dotnet -o publish/dotnet
        background: true

      - name: Build go
        id: build-go
        run: go build -o ../../publish/go/
        working-directory: ./src/go/
        background: true

      - name: Build go-db
        id: build-go-db
        run: go build -o ../../publish/go-db/
        working-directory: ./src/go-db/
        background: true

      - name: Check build results
        run: ls -l ./publish/
        continue-on-error: true

      # if not allowed
      - name: Wait background job
        wait: [build-dotnet]

      - name: Check build results after wait
        run: ls -lR ./publish/

  wait-all:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build dotnet
        id: build-dotnet
        run: dotnet build ./src/dotnet -o publish/dotnet
        background: true

      - name: Build go
        id: build-go
        run: go build -o ../../publish/go/
        working-directory: ./src/go/
        background: true

      - name: Build go-db
        id: build-go-db
        run: go build -o ../../publish/go-db/
        working-directory: ./src/go-db/
        background: true

      - name: Check build results
        run: ls -l ./publish/
        continue-on-error: true

      # if not allowed
      - name: Wait for all services to stop
        wait-all:

      - name: Check build results after wait
        run: ls -lR ./publish/

  no-wait:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build dotnet
        id: build-dotnet
        run: dotnet build ./src/dotnet -o publish/dotnet
        background: true

      - name: Build go
        id: build-go
        run: go build -o ../../publish/go/
        working-directory: ./src/go/
        background: true

      - name: Build go-db
        id: build-go-db
        run: go build -o ../../publish/go-db/
        working-directory: ./src/go-db/
        background: true

      - name: Check build results
        run: ls -l ./publish/
        continue-on-error: true

      - name: Some long running task
        run: sleep 30

      - name: Check build results after wait
        run: ls -lR ./publish/
