name: parallel (parallel)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  parallel:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      # parallel not allowed:
      # nested parallel: `parallel.parallel`
      # if section: `parallel.if:`
      - parallel:
          - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            with:
              persist-credentials: false
          - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
            with:
              dotnet-version: 10.0.x
      # parallel waits for all steps to complete before continuing
      - parallel:
          - name: Build dotnet
            run: dotnet build ./src/dotnet -o publish/dotnet

          - name: Build go
            run: go build -o ../../publish/go/
            working-directory: ./src/go/

          - name: Build go-db
            run: go build -o ../../publish/go-db/
            working-directory: ./src/go-db/

          # can use if condition in parallel
          - run: echo foo
            if: always()

      # all published artifacts should be present at this point
      - name: Check build results
        run: ls -l ./publish/
