name: parallel (parallel)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  parallel:
    permission:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - parallel:
          - name: Build dotnet
            run: dotnet build ./src/dotnet -o publish/dotnet

          - name: Build go
            run: go build -o ../../publish/go/
            working-directory: ./src/go/

          - name: Build go-build
            run: go build -o ../../publish/go-build/
            working-directory: ./src/go-build/

      - name: Check build results
        run: ls -l ./publish/

      - name: Wait for all services to stop
        wait-all:

      - name: Check build results after wait
        run: ls -l ./publish/
