name: runners

on:
  workflow_dispatch:

jobs:
  runners:
    permissions: {}
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04-arm
          - xcode-27
          - windows-11-arm
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 1
    steps:
      - name: echo
        run: echo "Hello world!"
